name: Unit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cmake
      run: sudo apt-get install cmake
    - name: Install C Unit
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v2
    
      
    - name: make all
      run:  make -C ffff-main/
    - name: Change mode
      run: cd ffff-main && chmod a+x 1all.out
    - name: unit test
      run: cd ffff-main && ./1all.out
